const CATALOGO_MODELOS = {
  "kay": {
    "nome": "Kay",
    "pecas": [
      { "nome": "Acelerador de punho", "preco": 125.00, "peso": "10gr", "img": "img/kay/Acelerador de punho $125,00  10gr.jpeg," },
      { "nome": "Alça encosto", "preco": 115.00, "peso": "55gr", "img": "img/kay/Alça encosto $115,00 55gr.jpeg" },
      { "nome": "Amortecedor dianteiro bengala", "preco": 85.00, "peso": "1,35kg", "img": "img/kay/Amortecedor dianteiro bengala $85,00  1,35kg  cada.jpeg" },
      { "nome": "Amortecedor traseiro", "preco": 85.00, "peso": "1kg", "img": "img/kay/Amortecedor traseiro $85,00 1kg cada.jpeg" },
      { "nome": "Apara barro dianteiro", "preco": 45.00, "peso": "60gr", "img": "img/kay/apara barro dianteiro $45,00 60gr.jpeg" },
      { "nome": "Aro dianteiro", "preco": 206.00, "peso": "2,30kg", "img": "img/kay/Aro dianteiro (atras) $206,00 2,30kg.jpeg" },
      { "nome": "Assoalho", "preco": 126.00, "peso": "90gr", "img": "img/kay/Assoalho $126,00 90gr.jpeg" },
      { "nome": "Assoalho inferior", "preco": 45.00, "peso": "25gr", "img": "img/kay/Assoalho inferior $45,00 25gr (foto de lado).jpeg" },
      { "nome": "Balança", "preco": 225.00, "peso": "1,90kg", "img": "img/kay/Balança $225,00 1,90kg.jpeg" },
      { "nome": "Banco", "preco": 75.00, "peso": "1,60kg", "img": "img/kay/Banco 1,60kg.jpeg" },
      { "nome": "Banco conjugado", "preco": 225.00, "peso": "1,60kg", "img": "img/kay/Banco conjugado $225,00 1,60kg..jpeg" },
      { "nome": "Barra bateria", "preco": 20.00, "peso": "20gr", "img": "img/kay/Barra bateria $20,00 20gr.jpeg" },
      { "nome": "Bateria 12h", "preco": null, "peso": null, "img": "img/kay/Bateria 12h.jpeg" },
      { "nome": "Bateria grafeno 12v 35ah", "preco": 600.00, "peso": "10,25kg", "img": "img/kay/Bateria grafeno 12v 35ah $600,00 10,25kg.jpeg" },
      { "nome": "Baú", "preco": 45.00, "peso": "1kg", "img": "img/kay/Baú $45,00 1kg..jpeg" },
      { "nome": "Buzina", "preco": 25.00, "peso": "10gr", "img": "img/kay/Buzina $25,00 10 gr.jpeg" },
      { "nome": "Cabo de freio traseiro", "preco": 106.00, "peso": "25gr", "img": "img/kay/Cabo de freio traseiro $106,00 25gr.jpeg" },
      { "nome": "Cabo motor módulo", "preco": 47.00, "peso": "10gr", "img": "img/kay/Cabo motor módulo $47,00 10gr.jpeg" },
      { "nome": "Carenagem escudo", "preco": 189.00, "peso": "45gr", "img": "img/kay/carenagem escudo $189,00 45gr.jpeg" },
      { "nome": "Carenagem farol completa", "preco": 269.00, "peso": "60gr", "img": "img/kay/Carenagem farol completa $269,00 60gr.jpeg" },
      { "nome": "Carenagem guidão", "preco": 42.00, "peso": "5gr", "img": "img/kay/Carenagem guidão $42,00 5gr.jpeg" },
      { "nome": "Carenagem lateral", "preco": 56.00, "peso": "15gr", "img": "img/kay/Carenagem lateral 15gr.jpeg" },
      { "nome": "Carenagem lateral direita", "preco": 65.00, "peso": "15gr", "img": "img/kay/Carenagem lateral $65,00 15gr direita.jpeg" },
      { "nome": "Carenagem painel", "preco": 42.00, "peso": "10gr", "img": "img/kay/Carenagem painel $42,00 10gr..jpeg" },
      { "nome": "Cavalete", "preco": 125.00, "peso": "1,35kg", "img": "img/kay/cavalete $125,00 1,35kg.jpeg" },
      { "nome": "Chicote", "preco": 315.00, "peso": "55gr", "img": "img/kay/Chicote $315,00 55gr.jpeg" },
      { "nome": "Conjunto botões direito", "preco": 56.00, "peso": "10gr", "img": "img/kay/Conjunto botões direito $56,00 10gr.jpeg" },
      { "nome": "Conjunto botões esquerdo", "preco": 56.00, "peso": "10gr", "img": "img/kay/Conjunto botões esquerdo $56,00 10gr.jpeg" },
      { "nome": "Conjunto cabo bateria", "preco": 35.00, "peso": "10gr", "img": "img/kay/Conjunto cabo bateria $35,00 10gr o conjunto.jpeg" },
      { "nome": "Conjunto de direção", "preco": 67.00, "peso": "10gr", "img": "img/kay/Conjunto de direção $67,00 10gr.jpeg" },
      { "nome": "Conversor", "preco": 52.00, "peso": "10gr", "img": "img/kay/Conversor $52,00 10gr.jpeg" },
      { "nome": "Descanso", "preco": 75.00, "peso": "30gr", "img": "img/kay/descanso $75,00  30gr.jpeg" },
      { "nome": "Disco de freio", "preco": 52.00, "peso": "55gr", "img": "img/kay/Disco de freio $52,00 55gr.jpeg" },
      { "nome": "Disjuntor", "preco": 54.00, "peso": "10gr", "img": "img/kay/Disjuntor $54,00 10gr.jpeg" },
      { "nome": "Eixo dianteiro", "preco": 35.00, "peso": "30gr", "img": "img/kay/Eixo dianteiro $35,00 30gr.jpeg" },
      { "nome": "Encosto frente", "preco": null, "peso": "55gr", "img": "img/kay/Encosto frente 55gr.jpeg" },
      { "nome": "Encosto garupa", "preco": 75.00, "peso": "55gr", "img": "img/kay/Encosto garupa $75,00 55gr.jpeg" },
      { "nome": "Farol dianteiro", "preco": 145.00, "peso": "80gr", "img": "img/kay/Farol dianteiro $145,00 80gr.jpeg" },
      { "nome": "Filete carenagem", "preco": 25.00, "peso": "10gr", "img": "img/kay/Filete carenagem $25,00 10gr.jpeg" },
      { "nome": "Freio tambor", "preco": 118.00, "peso": "55gr", "img": "img/kay/Freio tambor $118,00 55gr.jpeg" },
      { "nome": "Guidão", "preco": 115.00, "peso": "90gr", "img": "img/kay/Guidão $115,00 90gr.jpeg" },
      { "nome": "Ignição", "preco": 126.00, "peso": "20gr", "img": "img/kay/Ignição $126,00 20gr.jpeg" },
      { "nome": "Lanterna traseira", "preco": 75.00, "peso": "60gr", "img": "img/kay/Lanterna traseira $75,00 60gr.jpeg" },
      { "nome": "Luz placa", "preco": 25.00, "peso": "5gr", "img": "img/kay/Luz placa $25,00 5gr.jpeg" },
      { "nome": "Manete direito", "preco": 75.00, "peso": "10gr", "img": "img/kay/Manete direito $75,00 10gr.jpeg" },
      { "nome": "Manete direito hidraulico completo", "preco": 225.00, "peso": "1,30kg", "img": "img/kay/Manete direito hidraulico completo $225,00  1,30kg.jpeg" },
      { "nome": "Manete esquerdo com sensor", "preco": 107.00, "peso": "20gr", "img": "img/kay/Manete esquerdo com sensor $107,00 20gr.jpeg" },
      { "nome": "Manopla", "preco": 42.00, "peso": "10gr", "img": "img/kay/Manopla $42,00 10gr.jpeg" },
      { "nome": "Mesa inferior", "preco": 211.00, "peso": "1,95kg", "img": "img/kay/Mesa inferior $211,00 1,95kg.jpeg" },
      { "nome": "Modulo", "preco": 354.00, "peso": "60gr", "img": "img/kay/modulo $354,00 60gr.jpeg" },
      { "nome": "Mola", "preco": null, "peso": "5gr", "img": "img/kay/Mola 5gr.jpeg" },
      { "nome": "Motor 100w", "preco": 1250.00, "peso": "7kg", "img": "img/kay/Motor 100w $1250,00 7kg.jpeg" },
      { "nome": "Painel com alarme e tag", "preco": 135.00, "peso": "25gr", "img": "img/kay/Painel com alarme e tag $135,00 25gr.jpeg" },
      { "nome": "Paralama traseiro", "preco": 45.00, "peso": "25gr", "img": "img/kay/paralama traseiro $45,00 25gr.jpeg" },
      { "nome": "Pedaleira com chapa", "preco": 57.00, "peso": "50gr", "img": "img/kay/Pedaleira com chapa $57,00 50gr.jpeg" },
      { "nome": "Pedaleira sem chapa", "preco": 47.00, "peso": "25gr", "img": "img/kay/Pedaleira sem chapa $47,00 25gr.jpeg" },
      { "nome": "Placa", "preco": null, "peso": "5gr", "img": "img/kay/Placa 5gr.jpeg" },
      { "nome": "Plástico lateral direito", "preco": 56.00, "peso": "15gr", "img": "img/kay/Plástico lateral direito $56,00 15gr cada.jpeg" },
      { "nome": "Plástico lateral esquerdo", "preco": 45.00, "peso": "15gr", "img": "img/kay/Plástico lateral esquerdo 15gr.jpeg" },
      { "nome": "Plástico rabeta inferior", "preco": 35.00, "peso": "10gr", "img": "img/kay/Plástico rabeta inferior $35,00 10gr.jpeg" },
      { "nome": "Plástico tomada", "preco": 45.00, "peso": "25gr", "img": "img/kay/Plástico tomada $45,00 25gr.jpeg" },
      { "nome": "Pneu aro 10 3.0", "preco": 206.00, "peso": "1,65kg", "img": "img/kay/Pneu aro 10 3.0 $206,00 1,65kg.jpeg" },
      { "nome": "Pneu dianteiro", "preco": null, "peso": "4,55kg", "img": "img/kay/Pneu dianteiro 4,55kg.jpeg" },
      { "nome": "Porta sacola", "preco": 15.00, "peso": "5gr", "img": "img/kay/Porta sacola $15,00 5 grama.jpeg" },
      { "nome": "Porta treco", "preco": 75.00, "peso": "1kg", "img": "img/kay/Porta treco $75,00 1kg.jpeg" },
      { "nome": "Protetor de balança", "preco": 85.00, "peso": "15gr", "img": "img/kay/Protetor de balança $85,00 15gr.jpeg" },
      { "nome": "Páralama dianteiro", "preco": 190.00, "peso": "35gr", "img": "img/kay/Páralama dianteiro $190,00 35gr.jpeg" },
      { "nome": "Quadro", "preco": 450.00, "peso": "15,40kg", "img": "img/kay/Quadro $450,00 15,40kg.jpeg" },
      { "nome": "Rabeta", "preco": 55.00, "peso": "35gr", "img": "img/kay/Rabeta $55,00 35gr.jpeg" },
      { "nome": "Refletor traseira", "preco": 25.00, "peso": "5gr", "img": "img/kay/refletor traseira $25,00 5gr.jpeg" },
      { "nome": "Seta dianteira", "preco": 64.00, "peso": "5gr", "img": "img/kay/Seta dianteira $64,00 5 gr cada.jpeg" },
      { "nome": "Tapete", "preco": 70.00, "peso": "50gr", "img": "img/kay/Tapete $70,00 50gr.jpeg" },
      { "nome": "Tomada", "preco": 35.00, "peso": "5gr", "img": "img/kay/Tomada $35,00 5gr.jpeg" },
      { "nome": "Trava do banco", "preco": 35.00, "peso": "5gr", "img": "img/kay/Trava do banco $35,00 5gr.jpeg" },
      { "nome": "USB", "preco": 25.00, "peso": "5gr", "img": "img/kay/USB $25,00  5gr.jpeg" }
    ]
  },
  "jaya": {
    "nome": "JAYA",
    "pecas": [
      { "nome": "Acelerador", "preco": 125.00, "peso": "15gr", "img": "img/jaya/Acelerador 15gr.jpeg" },
      { "nome": "Amortecedor traseiro", "preco": null, "peso": "70gr", "img": "img/jaya/Amortecedor traseiro  70gr cada.jpeg" },
      { "nome": "Aro", "preco": 206.00, "peso": "2kg", "img": "img/jaya/Aro 2kg.jpeg" },
      { "nome": "Assoalho", "preco": 125.00, "peso": "35gr", "img": "img/jaya/Assoalho 35gr.jpeg" },
      { "nome": "Balança", "preco": 220.00, "peso": "1,40kg", "img": "img/jaya/Balança 1,40kg.jpeg" },
      { "nome": "Banco passageiro", "preco": null, "peso": "30gr", "img": "img/jaya/Banco passageiro 30gr.jpeg" },
      { "nome": "Bateria 12v 20 grafeno", "preco": null, "peso": "7,10kg", "img": "img/jaya/Bateria 12v 20 grafeno 7,10kg.jpeg" },
      { "nome": "Borracha acabamento banco", "preco": null, "peso": "5gr", "img": "img/jaya/Borracha acabamento banco 5gr.jpeg" },
      { "nome": "Buzina", "preco": 25.00, "peso": "10gr", "img": "img/jaya/Buzina 10gr.jpeg" },
      { "nome": "Cabo do motor", "preco": null, "peso": "10gr", "img": "img/jaya/cabo do motor 10gr.jpeg" },
      { "nome": "Cabo Freio", "preco": 106.80, "peso": "25gr", "img": "img/jaya/Cabo Freio 25gr.jpeg" },
      { "nome": "Cabo Freio dianteiro", "preco": null, "peso": "15gr", "img": "img/jaya/Cabo Freio dianteiro 15gr.jpeg" },
      { "nome": "Caixa bateria", "preco": 45.00, "peso": "35gr", "img": "img/jaya/Caixa bateria 35gr.jpeg" },
      { "nome": "Carenagem baú", "preco": 89.00, "peso": "25gr", "img": "img/jaya/Carenagem baú 25 gr cada.jpeg" },
      { "nome": "Carenagem farol", "preco": null, "peso": "50gr", "img": "img/jaya/Carenagem farol 50gr.jpeg" },
      { "nome": "Carenagem filete", "preco": null, "peso": "5gr", "img": "img/jaya/Carenagem filete 5gr.jpeg" },
      { "nome": "Carenagem guidão", "preco": 42.00, "peso": "20gr", "img": "img/jaya/Carenagem guidão 20gr.jpeg" },
      { "nome": "Carenagem lateral", "preco": 56.00, "peso": "10gr", "img": "img/jaya/Carenagem lateral 10gr cada.jpeg" },
      { "nome": "CARENAGEM PAINEL", "preco": 42.00, "peso": "15gr", "img": "img/jaya/CARENAGEM PAINEL PESO 15GR.jpeg" },
      { "nome": "Carenagem rabeta", "preco": 55.00, "peso": "5gr", "img": "img/jaya/Carenagem rabeta 5gr.jpeg" },
      { "nome": "Cavalete", "preco": 125.00, "peso": "90gr", "img": "img/jaya/Cavalete 90gr.jpeg" },
      { "nome": "Chicote", "preco": 315.00, "peso": "45gr", "img": "img/jaya/Chicote 45gr.jpeg" },
      { "nome": "Conjunto cabo bateria", "preco": null, "peso": "5gr", "img": "img/jaya/Conjunto cabo bateria 5gr.jpeg" },
      { "nome": "Conjunto de botão esquerdo", "preco": null, "peso": "15gr", "img": "img/jaya/conjunto de botão esquerdo 15gr.jpeg" },
      { "nome": "Conversor", "preco": 52.00, "peso": "10gr", "img": "img/jaya/Conversor 10gr.jpeg" },
      { "nome": "Encosto atrás", "preco": null, "peso": null, "img": "img/jaya/Encosto atrás.jpeg" },
      { "nome": "Encosto frente", "preco": null, "peso": "60gr", "img": "img/jaya/Encosto frente 60gr.jpeg" },
      { "nome": "Farol", "preco": 269.00, "peso": "40gr", "img": "img/jaya/Farol 40gr.jpeg" },
      { "nome": "Freio tambor", "preco": 118.80, "peso": "45gr", "img": "img/jaya/Freio tambor 45gr.jpeg" },
      { "nome": "Freio tambor traseiro", "preco": 118.80, "peso": "50gr", "img": "img/jaya/freio tambor traseiro  50gr.jpeg" },
      { "nome": "Guidão", "preco": 115.00, "peso": "1,10kg", "img": "img/jaya/guidão 1,10kg.jpeg" },
      { "nome": "Ignição", "preco": 126.00, "peso": "5gr", "img": "img/jaya/Ignição 5gr.jpeg" },
      { "nome": "Lanterna logo", "preco": null, "peso": "10gr", "img": "img/jaya/Lanterna  logo 10gr.jpeg" },
      { "nome": "Lanterna traseira", "preco": 75.00, "peso": "15gr", "img": "img/jaya/Lanterna traseira 15 gr.jpeg" },
      { "nome": "Manete direito", "preco": 75.00, "peso": "5gr", "img": "img/jaya/Manete direito 5gr.jpeg" },
      { "nome": "Manete esquerdo", "preco": 107.00, "peso": "10gr", "img": "img/jaya/Manete esquerdo 10gr.jpeg" },
      { "nome": "Manopla", "preco": 42.00, "peso": "10gr", "img": "img/jaya/Manopla 10gr.jpeg" },
      { "nome": "Mesa inferior", "preco": 211.00, "peso": "1,20kg", "img": "img/jaya/Mesa inferior 1,20kg.jpeg" },
      { "nome": "Motor", "preco": 1250.00, "peso": "6,90kg", "img": "img/jaya/Motor 6,90kg.jpeg" },
      { "nome": "Módulo", "preco": 354.00, "peso": "60gr", "img": "img/jaya/Módulo 60gr.jpeg" },
      { "nome": "PAINEL COM TAG", "preco": null, "peso": "30gr", "img": "img/jaya/PAINEL COM TAG 30GR.jpeg" },
      { "nome": "Par de bengala", "preco": null, "peso": "90gr", "img": "img/jaya/Par de bengala 90gr cada.jpeg" },
      { "nome": "Par de pedaleira", "preco": null, "peso": "25gr", "img": "img/jaya/Par de pedaleira 25gr cada.jpeg" },
      { "nome": "Par de retrovisor", "preco": null, "peso": "35gr", "img": "img/jaya/Par de retrovisor 35gr.jpeg" },
      { "nome": "Par de setas", "preco": null, "peso": "15gr", "img": "img/jaya/Par de setas 15gr.jpeg" },
      { "nome": "Para barro", "preco": null, "peso": "10gr", "img": "img/jaya/Para barro 10gr.jpeg" },
      { "nome": "Pezinho", "preco": null, "peso": "35gr", "img": "img/jaya/Pezinho  35gr.jpeg" },
      { "nome": "Peça de direção", "preco": null, "peso": "10gr", "img": "img/jaya/Peça de direção 10gr.jpeg" },
      { "nome": "Placa", "preco": null, "peso": "5gr", "img": "img/jaya/Placa 5gr.jpeg" },
      { "nome": "Plástico acabamento", "preco": null, "peso": "20gr", "img": "img/jaya/Plástico acabamento 20gr.jpeg" },
      { "nome": "Plástico banco", "preco": null, "peso": "25gr", "img": "img/jaya/Plástico banco 25gr.jpeg" },
      { "nome": "Plástico banco passageiro", "preco": null, "peso": "20gr", "img": "img/jaya/Plástico banco passageiro 20gr.jpeg" },
      { "nome": "Plástico chassi 5 chassi", "preco": null, "peso": null, "img": "img/jaya/Plástico chassi 5 chassi.jpeg" },
      { "nome": "Plástico lateral", "preco": 45.00, "peso": "30gr", "img": "img/jaya/Plástico lateral 30gr cada.jpeg" },
      { "nome": "Plástico tomada", "preco": null, "peso": "5gr", "img": "img/jaya/Plástico tomada 5gr.jpeg" },
      { "nome": "Plástico tomada (sem tomada)", "preco": null, "peso": "10gr", "img": "img/jaya/Plástico tomada (sem tomada) 10gr.jpeg" },
      { "nome": "Pneu 2.75 - 10", "preco": null, "peso": "1,60kg", "img": "img/jaya/Pneu 2.75 - 10    1,60kg.jpeg" },
      { "nome": "Porta treco", "preco": 75.00, "peso": "60gr", "img": "img/jaya/Porta treco 60gr.jpeg" },
      { "nome": "Protetor balança e pezinho lateral", "preco": 220.00, "peso": "20gr", "img": "img/jaya/Protetor balança e pezinho lateral 20gr o par.jpeg" },
      { "nome": "Páralama dianteiro", "preco": 190.80, "peso": "25gr", "img": "img/jaya/Páralama dianteiro 25gr.jpeg" },
      { "nome": "QUADRO JAYA", "preco": 450.00, "peso": "9,40kg", "img": "img/jaya/QUADRO JAYA 9,40KG.jpeg" },
      { "nome": "Rabeta", "preco": 55.00, "peso": "25gr", "img": "img/jaya/Rabeta 25gr.jpeg" },
      { "nome": "Relé", "preco": null, "peso": "5gr", "img": "img/jaya/Relé 5gr.jpeg" },
      { "nome": "Suporte manete sensor", "preco": null, "peso": "15gr", "img": "img/jaya/Suporte manete sensor  15gr.jpeg" },
      { "nome": "Suporte sensor do manete", "preco": null, "peso": "15gr", "img": "img/jaya/Suporte sensor do manete 15 gr.jpeg" },
      { "nome": "Tomada", "preco": 35.00, "peso": "10gr", "img": "img/jaya/Tomada 10gr.jpeg" }
    ]
  },
  "juna-smart": {
    "nome": "JUNA SMART",
    "pecas": [
      { "nome": "Acelerador", "preco": 125.00, "peso": "10gr", "img": "img/juna-smart/acelerador  10gr.jpeg" },
      { "nome": "Alarme", "preco": 126.00, "peso": "5gr", "img": "img/juna-smart/alarme 5gr.jpeg" },
      { "nome": "Amortecedor dianteiro", "preco": null, "peso": "1,15kg", "img": "img/juna-smart/Amortecedor dianteiro 1,15KG CADA.jpeg" },
      { "nome": "Amortecedor traseiro", "preco": null, "peso": "1kg", "img": "img/juna-smart/Amortecedor traseiro  1KG CADA.jpeg" },
      { "nome": "Aro", "preco": 206.00, "peso": "2,75kg", "img": "img/juna-smart/aro  2,75kg.jpeg" },
      { "nome": "Assoalho", "preco": 125.00, "peso": "35gr", "img": "img/juna-smart/assoalho 35gr.jpeg" },
      { "nome": "BALANCA", "preco": 220.00, "peso": "2kg", "img": "img/juna-smart/BALANCA 2KG.jpeg" },
      { "nome": "Banco", "preco": 75.00, "peso": "1,35kg", "img": "img/juna-smart/banco 1,35kg foto dentro.jpeg" },
      { "nome": "Banco frente", "preco": null, "peso": "1,35kg", "img": "img/juna-smart/banco 1,35kg frente.jpeg" },
      { "nome": "Barra lateral", "preco": null, "peso": "35gr", "img": "img/juna-smart/Barra lateral 35GR CADA.jpeg" },
      { "nome": "Bateria", "preco": 298.80, "peso": "7,05kg", "img": "img/juna-smart/bateria 7,05kg.jpeg" },
      { "nome": "Buzina", "preco": 25.00, "peso": "10gr", "img": "img/juna-smart/Buzina 10GR.jpeg" },
      { "nome": "Cabo freio", "preco": 106.80, "peso": "25gr", "img": "img/juna-smart/cabo freio 25GR.jpeg" },
      { "nome": "Cabo ignição", "preco": 126.00, "peso": "10gr", "img": "img/juna-smart/cabo ignição 10gr.jpeg" },
      { "nome": "Cabo motor módulo", "preco": null, "peso": "10gr", "img": "img/juna-smart/cabo motor módulo 10gr.jpeg" },
      { "nome": "Caixa da bateria", "preco": null, "peso": "75gr", "img": "img/juna-smart/Caixa da bateria 75GR.jpeg" },
      { "nome": "Caixa de som da juna smart", "preco": null, "peso": "15gr", "img": "img/juna-smart/caixa de som da juna smart 15gr.jpeg" },
      { "nome": "Carenagem baú", "preco": 89.00, "peso": "25gr", "img": "img/juna-smart/carenagem baú 25gr cada.jpeg" },
      { "nome": "Carenagem farol", "preco": null, "peso": "50gr", "img": "img/juna-smart/carenagem farol 50GR.jpeg" },
      { "nome": "Carenagem guidão", "preco": 42.00, "peso": "20gr", "img": "img/juna-smart/carenagem guidão 20gr.jpeg" },
      { "nome": "Carenagem lateral", "preco": 56.00, "peso": "10gr", "img": "img/juna-smart/carenagem lateral 10gr cada.jpeg" },
      { "nome": "Carenagem rabeta", "preco": 55.00, "peso": "10gr", "img": "img/juna-smart/Carenagem rabeta 10GR.jpeg" },
      { "nome": "Cavalete central", "preco": 125.00, "peso": "1,10kg", "img": "img/juna-smart/cavalete central 1,10kg.jpeg" },
      { "nome": "Chicote", "preco": 315.00, "peso": "50gr", "img": "img/juna-smart/chicote 50GR.jpeg" },
      { "nome": "Conector da bateria", "preco": null, "peso": "5gr", "img": "img/juna-smart/conector da bateria 5gr.jpeg" },
      { "nome": "Conjunto de botão direito", "preco": null, "peso": "10gr", "img": "img/juna-smart/conjunto de botão direito  10gr.jpeg" },
      { "nome": "Conjunto de botões esquerdo", "preco": null, "peso": "10gr", "img": "img/juna-smart/conjunto de botões esquerdo 10gr.jpeg" },
      { "nome": "Conjunto de direção", "preco": 57.00, "peso": "10gr", "img": "img/juna-smart/conjunto de direção 10gr.jpeg" },
      { "nome": "Conversor", "preco": 52.00, "peso": "10gr", "img": "img/juna-smart/conversor 10gr.jpeg" },
      { "nome": "Disco do freio", "preco": null, "peso": "55gr", "img": "img/juna-smart/disco do freio 55gr.jpeg" },
      { "nome": "Escudo", "preco": 189.00, "peso": "30gr", "img": "img/juna-smart/escudo 30gr.jpeg" },
      { "nome": "Farol", "preco": 269.00, "peso": "65gr", "img": "img/juna-smart/Farol 65GR.jpeg" },
      { "nome": "Filete carenagem bau", "preco": 45.00, "peso": "5gr", "img": "img/juna-smart/filete carenagem bau 5gr.jpeg" },
      { "nome": "Freio hidráulico dianteiro", "preco": 225.00, "peso": "1kg", "img": "img/juna-smart/freio hidráulico dianteiro  1kg.jpeg" },
      { "nome": "Freio tambor traseiro", "preco": 118.80, "peso": "55gr", "img": "img/juna-smart/freio tambor traseiro  55gr.jpeg" },
      { "nome": "Guidão", "preco": 115.00, "peso": "90gr", "img": "img/juna-smart/guidão 90gr.jpeg" },
      { "nome": "Iluminação logo", "preco": null, "peso": "5gr", "img": "img/juna-smart/iluminação logo 5gr.jpeg" },
      { "nome": "Lanterna traseira", "preco": 75.00, "peso": "15gr", "img": "img/juna-smart/lanterna traseira 15GR.jpeg" },
      { "nome": "Manete direito", "preco": 75.00, "peso": "10gr", "img": "img/juna-smart/manete direito 10gr.jpeg" },
      { "nome": "Manete esquerdo", "preco": 107.00, "peso": "5gr", "img": "img/juna-smart/manete esquerdo 5 gr.jpeg" },
      { "nome": "Manopla", "preco": 42.00, "peso": "10gr", "img": "img/juna-smart/manopla  10gr.jpeg" },
      { "nome": "Mesa inferior", "preco": 211.00, "peso": "1,60kg", "img": "img/juna-smart/mesa inferior 1,60kg.jpeg" },
      { "nome": "Miolo trava do guidão", "preco": 115.00, "peso": "25gr", "img": "img/juna-smart/miolo trava do guidão 25gr.jpeg" },
      { "nome": "Motor", "preco": 1250.00, "peso": "7,10kg", "img": "img/juna-smart/motor 7,10kg.jpeg" },
      { "nome": "Módulo", "preco": 354.00, "peso": "60gr", "img": "img/juna-smart/Módulo 60GR.jpeg" },
      { "nome": "Par de pisca", "preco": null, "peso": "5gr", "img": "img/juna-smart/par de pisca 5gr.jpeg" },
      { "nome": "Para barro dianteiro", "preco": null, "peso": "35gr", "img": "img/juna-smart/para barro dianteiro 35gr.jpeg" },
      { "nome": "Paralama dianteiro", "preco": 190.80, "peso": "25gr", "img": "img/juna-smart/paralama dianteiro 25gr.jpeg" },
      { "nome": "Paralama traseiro", "preco": 166.80, "peso": "25gr", "img": "img/juna-smart/paralama traseiro 25gr.jpeg" },
      { "nome": "Pezinho", "preco": null, "peso": "25gr", "img": "img/juna-smart/pezinho  25gr.jpeg" },
      { "nome": "Plástico assoalho traseiro", "preco": 125.00, "peso": "10gr", "img": "img/juna-smart/plástico assoalho traseiro  10gr.jpeg" },
      { "nome": "Plástico farol traseiro", "preco": null, "peso": "10gr", "img": "img/juna-smart/plástico farol traseiro 10GR.jpeg" },
      { "nome": "Plástico rabeta", "preco": 55.00, "peso": "10gr", "img": "img/juna-smart/plástico rabeta 10gr.jpeg" },
      { "nome": "Plástico tomada", "preco": null, "peso": "25gr", "img": "img/juna-smart/plástico tomada 25gr.jpeg" },
      { "nome": "Pneu 2.25-12", "preco": null, "peso": "1,55kg", "img": "img/juna-smart/pneu 2.25-12    1,55kg.jpeg" },
      { "nome": "Porta Treco", "preco": 75.00, "peso": "55gr", "img": "img/juna-smart/porta Treco 55gr.jpeg" },
      { "nome": "Protetor de balança", "preco": 144.00, "peso": "15gr", "img": "img/juna-smart/Protetor de balança 15GR CADA.jpeg" },
      { "nome": "Protetor módulo", "preco": null, "peso": "15gr", "img": "img/juna-smart/protetor módulo  15gr.jpeg" },
      { "nome": "Pé de apoio traseiro", "preco": null, "peso": "15gr", "img": "img/juna-smart/pé de apoio traseiro 15gr cada.jpeg" },
      { "nome": "Pé lateral", "preco": null, "peso": "25gr", "img": "img/juna-smart/pé lateral 25gr cada.jpeg" },
      { "nome": "Quadro", "preco": 450.00, "peso": "10,45kg", "img": "img/juna-smart/quadro 10,45kg.jpeg" },
      { "nome": "Rabeta", "preco": 55.00, "peso": "80gr", "img": "img/juna-smart/rabeta  80gr..jpeg" },
      { "nome": "Suporte da placa", "preco": null, "peso": "5gr", "img": "img/juna-smart/suporte da placa 5gr.jpeg" },
      { "nome": "Suporte do Cesto", "preco": null, "peso": "1,90kg", "img": "img/juna-smart/suporte do Cesto 1,90kg.jpeg" },
      { "nome": "Suporte manete direito com sensor", "preco": 75.00, "peso": "10gr", "img": "img/juna-smart/suporte manete direito com sensor 10gr.jpeg" },
      { "nome": "Tomada", "preco": 35.00, "peso": "5gr", "img": "img/juna-smart/tomada 5gr.jpeg" },
      { "nome": "Trava do banco", "preco": null, "peso": "5gr", "img": "img/juna-smart/trava do banco 5gr..jpeg" }
    ]
  },
  "luna": {
    "nome": "LUNA",
    "pecas": [
      { "nome": "Acelerador e conjunto de botão direito", "preco": null, "peso": "20gr", "img": "img/luna/Acelerador e conjunto de botão direito 20gr.jpeg" },
      { "nome": "Alarme", "preco": 126.00, "peso": "5gr", "img": "img/luna/alarme 5gr.jpeg" },
      { "nome": "Aro", "preco": 206.00, "peso": "1,45kg", "img": "img/luna/aro 1,45kg.jpeg" },
      { "nome": "Assoalho", "preco": 125.00, "peso": "30gr", "img": "img/luna/assoalho 30gr.jpeg" },
      { "nome": "Balanca", "preco": 220.00, "peso": "1,85kg", "img": "img/luna/balanca 1,85kg.jpeg" },
      { "nome": "Banco atras", "preco": null, "peso": "40gr", "img": "img/luna/Banco atras 40gr.jpeg" },
      { "nome": "Banco frente", "preco": null, "peso": "40gr", "img": "img/luna/banco frente 40gr.jpeg" },
      { "nome": "Banco Piloto", "preco": 75.00, "peso": "95gr", "img": "img/luna/Banco Piloto 95gr.jpeg" },
      { "nome": "Banco piloto atras", "preco": 75.00, "peso": "95gr", "img": "img/luna/banco piloto atras 95gr.jpeg" },
      { "nome": "Bateria", "preco": 298.80, "peso": "7,80kg", "img": "img/luna/bateria 7,80kg.jpeg" },
      { "nome": "BAU", "preco": 45.00, "peso": "75gr", "img": "img/luna/BAU 75GR.jpeg" },
      { "nome": "Buzina", "preco": 25.00, "peso": "5gr", "img": "img/luna/Buzina 5gr.jpeg" },
      { "nome": "Cabo Freio", "preco": 106.80, "peso": "20gr", "img": "img/luna/Cabo Freio 20gr.jpeg" },
      { "nome": "Carenagem", "preco": 269.00, "peso": "40gr", "img": "img/luna/Carenagem 40gr.jpeg" },
      { "nome": "Carenagem farol", "preco": null, "peso": "20gr", "img": "img/luna/carenagem farol 20gr.jpeg" },
      { "nome": "Cavalete", "preco": 125.00, "peso": "90gr", "img": "img/luna/cavalete 90gr.jpeg" },
      { "nome": "Cesto", "preco": null, "peso": "1,10kg", "img": "img/luna/Cesto Peso 1,10kg.jpeg" },
      { "nome": "Chicote da bateria", "preco": 315.00, "peso": "15gr", "img": "img/luna/chicote da bateria 15gr.jpeg" },
      { "nome": "Chicote principal", "preco": 315.00, "peso": "30gr", "img": "img/luna/chicote principal 30gr.jpeg" },
      { "nome": "Conj jogo direção", "preco": null, "peso": "10gr", "img": "img/luna/conj jogo direção 10gr.jpeg" },
      { "nome": "Conjunto de botões esquerdo", "preco": null, "peso": "5gr", "img": "img/luna/Conjunto de botões esquerdo 5gr.jpeg" },
      { "nome": "Corrente", "preco": null, "peso": "25gr", "img": "img/luna/corrente 25gr.jpeg" },
      { "nome": "Disco do freio", "preco": null, "peso": "55gr", "img": "img/luna/disco do freio 55gr.jpeg" },
      { "nome": "Encosto atras", "preco": null, "peso": "65gr", "img": "img/luna/encosto atras 65gr.jpeg" },
      { "nome": "Encosto frente", "preco": null, "peso": "65gr", "img": "img/luna/encosto frente 65gr.jpeg" },
      { "nome": "Farol", "preco": 269.00, "peso": "45gr", "img": "img/luna/Farol 45gr.jpeg" },
      { "nome": "Freio dianteiro e suporte do manete", "preco": null, "peso": "95gr", "img": "img/luna/freio dianteiro e suporte do manete 95gr.jpeg" },
      { "nome": "Freio tambor traseiro", "preco": 118.80, "peso": "50gr", "img": "img/luna/freio tambor traseiro 50gr.jpeg" },
      { "nome": "Guidão", "preco": 115.00, "peso": "1kg", "img": "img/luna/guidão 1kg.jpeg" },
      { "nome": "Lanterna traseira", "preco": 75.00, "peso": "15gr", "img": "img/luna/Lanterna traseira 15gr.jpeg" },
      { "nome": "Manete direito", "preco": 75.00, "peso": "5gr", "img": "img/luna/manete direito 5gr.jpeg" },
      { "nome": "Manete esquerdo", "preco": 107.00, "peso": "5gr", "img": "img/luna/manete esquerdo 5 gr.jpeg" },
      { "nome": "Manopla", "preco": 42.00, "peso": "25gr", "img": "img/luna/manopla 25gr.jpeg" },
      { "nome": "Mesa asta", "preco": null, "peso": "30gr", "img": "img/luna/mesa asta 30gr.jpeg" },
      { "nome": "Mesa inferior", "preco": 211.00, "peso": "1,55kg", "img": "img/luna/mesa inferior 1,55kg.jpeg" },
      { "nome": "Miolo", "preco": null, "peso": "5gr", "img": "img/luna/Miolo 5gr.jpeg" },
      { "nome": "Miolo da trava do banco", "preco": null, "peso": "5gr", "img": "img/luna/miolo da trava do banco 5gr.jpeg" },
      { "nome": "Motor", "preco": 1250.00, "peso": "6,05kg", "img": "img/luna/motor 6,05kg.jpeg" },
      { "nome": "Módulo", "preco": 354.00, "peso": "30gr", "img": "img/luna/Módulo  30gr.jpeg" },
      { "nome": "Painel", "preco": 42.00, "peso": "20gr", "img": "img/luna/painel 20gr.jpeg" },
      { "nome": "Par de seta", "preco": null, "peso": "5gr", "img": "img/luna/par de seta 5gr cada.jpeg" },
      { "nome": "Para barro traseiro", "preco": null, "peso": "10gr", "img": "img/luna/Para barro traseiro 10gr.jpeg" },
      { "nome": "Paralama dianteiro", "preco": 190.80, "peso": "20gr", "img": "img/luna/paralama dianteiro  20gr.jpeg" },
      { "nome": "Paralama traseiro", "preco": 166.80, "peso": "30gr", "img": "img/luna/paralama traseiro 30gr..jpeg" },
      { "nome": "Pedal", "preco": 57.00, "peso": "20gr", "img": "img/luna/pedal 20gr.jpeg" },
      { "nome": "Pedal traseiro", "preco": null, "peso": "20gr", "img": "img/luna/pedal traseiro  20gr cada.jpeg" },
      { "nome": "Pezinho", "preco": null, "peso": "25gr", "img": "img/luna/pezinho 25gr.jpeg" },
      { "nome": "Pisca traseiro", "preco": null, "peso": "5gr", "img": "img/luna/Pisca traseiro 5gr cada.jpeg" },
      { "nome": "Placa conector", "preco": null, "peso": "5gr", "img": "img/luna/placa conector 5gr.jpeg" },
      { "nome": "Plástico frontal", "preco": null, "peso": "15gr", "img": "img/luna/Plástico frontal 15gr.jpeg" },
      { "nome": "Plástico inferior garupa", "preco": null, "peso": "30gr", "img": "img/luna/plástico inferior garupa 30gr.jpeg" },
      { "nome": "Plástico lateral", "preco": 45.00, "peso": "35gr", "img": "img/luna/Plástico lateral 35gr cada lado.jpeg" },
      { "nome": "Plástico lateral paralama traseiro", "preco": 166.80, "peso": "5gr", "img": "img/luna/plástico lateral paralama traseiro 5gr cada.jpeg" },
      { "nome": "Plástico protetor da balança", "preco": 220.00, "peso": "10gr", "img": "img/luna/Plástico protetor da balança 10gr cada.jpeg" },
      { "nome": "Pneu 2.5 - 10 ---", "preco": null, "peso": "1,35kg", "img": "img/luna/Pneu 2.5 - 10  --- 1,35kg.jpeg" },
      { "nome": "Porta sacola", "preco": null, "peso": "5gr", "img": "img/luna/porta sacola 5gr.jpeg" },
      { "nome": "Porta Treco", "preco": 75.00, "peso": "25gr", "img": "img/luna/Porta Treco 25gr.jpeg" },
      { "nome": "Quadro", "preco": 450.00, "peso": "11,50kg", "img": "img/luna/quadro 11,50kg.jpeg" },
      { "nome": "Rele do pisca", "preco": null, "peso": "5gr", "img": "img/luna/rele do pisca 5gr.jpeg" },
      { "nome": "Suporte da placa e pisca traseiro", "preco": null, "peso": "15gr", "img": "img/luna/suporte da placa e pisca traseiro  15gr..jpeg" },
      { "nome": "Suporte do cesto", "preco": null, "peso": "65gr", "img": "img/luna/suporte do cesto 65gr.jpeg" },
      { "nome": "Suporte do painel", "preco": null, "peso": "10gr", "img": "img/luna/suporte do painel 10gr.jpeg" },
      { "nome": "Suporte manete com sensor", "preco": null, "peso": "10gr", "img": "img/luna/suporte manete com sensor 10gr.jpeg" },
      { "nome": "Suspensão dianteiro 1,05direito e esquerdo", "preco": null, "peso": "95gr", "img": "img/luna/suspensão dianteiro 1,05direito e 95 gr esquerdo.jpeg" },
      { "nome": "Suspensão traseiro", "preco": null, "peso": "60gr", "img": "img/luna/suspensão traseiro 60gr cada.jpeg" },
      { "nome": "Tomada do carregador", "preco": 346.80, "peso": "5gr", "img": "img/luna/tomada do carregador  5gr.jpeg" },
      { "nome": "Trava do banco", "preco": null, "peso": "20gr", "img": "img/luna/trava do banco 20gr.jpeg" }
    ]
  },
  "shaka": {
    "nome": "SHAKA",
    "pecas": [
      { "nome": "Acabamento lateral colorido", "preco": 15.00, "peso": "5gr", "img": "img/shaka/Acabamento lateral colorido  $15,00 5g und.jpeg" },
      { "nome": "Acabamento plastico placa", "preco": 15.00, "peso": "5gr", "img": "img/shaka/acabamento plastico placa $15,00 5g.jpeg" },
      { "nome": "Alarme completo", "preco": 126.00, "peso": "5gr", "img": "img/shaka/Alarme completo $126,00 5g.jpeg" },
      { "nome": "Amortecedor traseiro", "preco": 85.00, "peso": "1,15kg", "img": "img/shaka/Amortecedor traseiro $85,00 1,15kg und.jpeg" },
      { "nome": "Aro dianteiro aro 10", "preco": 206.00, "peso": "2,15kg", "img": "img/shaka/Aro dianteiro aro 10,  $206,00 2,15kg.jpeg" },
      { "nome": "Assoalho", "preco": 126.00, "peso": "60gr", "img": "img/shaka/Assoalho $126,00 60g.jpeg" },
      { "nome": "Balança traseira", "preco": 220.00, "peso": "2,35kg", "img": "img/shaka/Balança traseira  $220,00 2,35kg ..jpeg" },
      { "nome": "Banco garupa", "preco": 45.00, "peso": "45gr", "img": "img/shaka/Banco garupa $45,00 45g.jpeg" },
      { "nome": "Banco piloto", "preco": 75.00, "peso": "70gr", "img": "img/shaka/Banco piloto $75,00 70g (1).jpeg" },
      { "nome": "Bateria 12v 20ah grafeno", "preco": 450.00, "peso": "7,25kg", "img": "img/shaka/Bateria 12v 20ah  grafeno  $450,00. 7,25kg a unidade.jpeg" },
      { "nome": "Buzina", "preco": 25.00, "peso": "5gr", "img": "img/shaka/Buzina. $25,00 5g.jpeg" },
      { "nome": "Cabo de freio traseiro", "preco": 106.00, "peso": "25gr", "img": "img/shaka/Cabo de freio traseiro. $106,00  25g.jpeg" },
      { "nome": "Caixa da bateria", "preco": 45.00, "peso": "50gr", "img": "img/shaka/Caixa da bateria. $45,00 50g.jpeg" },
      { "nome": "Carenagem frontal", "preco": 269.00, "peso": "50gr", "img": "img/shaka/Carenagem frontal $269,00 50g.jpeg" },
      { "nome": "Carenagem inferior guidão", "preco": 55.00, "peso": "10gr", "img": "img/shaka/carenagem inferior guidão $55,00 10g.jpeg" },
      { "nome": "Carenagem lateral", "preco": 75.00, "peso": "20gr", "img": "img/shaka/carenagem lateral $75,00 20g cada.jpeg" },
      { "nome": "Carenagem peitoral", "preco": 85.00, "peso": "25gr", "img": "img/shaka/carenagem peitoral $85,00 25g.jpeg" },
      { "nome": "Chapa da bateria", "preco": 25.00, "peso": "40gr", "img": "img/shaka/Chapa da bateria $25,00 40g.jpeg" },
      { "nome": "Chicote conector bateria", "preco": 75.00, "peso": "20gr", "img": "img/shaka/chicote conector bateria $75,00 20g.jpeg" },
      { "nome": "Chicote principal", "preco": 315.00, "peso": "45gr", "img": "img/shaka/Chicote principal. $315,00 45g.jpeg" },
      { "nome": "Conjunto de botão direito + acelerador de punho", "preco": 201.00, "peso": "15gr", "img": "img/shaka/Conjunto de botão direito + acelerador de punho $201,00 .15g.jpeg" },
      { "nome": "Conjunto de botão esquerdo", "preco": 56.00, "peso": "5gr", "img": "img/shaka/Conjunto de botão esquerdo $56,00 5g.jpeg" },
      { "nome": "Conversor", "preco": 52.00, "peso": "10gr", "img": "img/shaka/Conversor. $52,00 10g.jpeg" },
      { "nome": "Descanso", "preco": 75.00, "peso": "15gr", "img": "img/shaka/Descanso $75,00 15g.jpeg" },
      { "nome": "Disco de freio", "preco": 52.00, "peso": "55gr", "img": "img/shaka/Disco de freio $52,00  55g.jpeg" },
      { "nome": "Disjuntor", "preco": 52.00, "peso": "10gr", "img": "img/shaka/Disjuntor. $52,00 10g.jpeg" },
      { "nome": "Eixo dianteiro", "preco": 48.00, "peso": "25gr", "img": "img/shaka/Eixo dianteiro. $48,00 25g.jpeg" },
      { "nome": "Encosto traseiro", "preco": 126.00, "peso": "70gr", "img": "img/shaka/Encosto traseiro $126,00 70g (1).jpeg" },
      { "nome": "Farol dianteiro", "preco": 145.00, "peso": "40gr", "img": "img/shaka/Farol dianteiro $145,00 40gr.jpeg" },
      { "nome": "Freio hidraulico completo", "preco": 225.00, "peso": "85gr", "img": "img/shaka/freio hidraulico completo $225,00. 85g.jpeg" },
      { "nome": "Freio tambor traseiro", "preco": 118.00, "peso": "50gr", "img": "img/shaka/Freio tambor traseiro. $118,00 50g.jpeg" },
      { "nome": "Ignição", "preco": 126.00, "peso": "55gr", "img": "img/shaka/Ignição $126,00 55g.jpeg" },
      { "nome": "Luz traseira", "preco": 75.00, "peso": "20gr", "img": "img/shaka/Luz traseira $75,00 20g.jpeg" },
      { "nome": "Manete direito", "preco": 65.00, "peso": "5gr", "img": "img/shaka/Manete direito $65,00. 5g.jpeg" },
      { "nome": "Manete esquerdo com sensor", "preco": 107.00, "peso": "15gr", "img": "img/shaka/Manete esquerdo com sensor $107,00. 15g.jpeg" },
      { "nome": "Mesa inferior", "preco": 211.00, "peso": "1,70gr", "img": "img/shaka/Mesa inferior. $211,00 1,70g.jpeg" },
      { "nome": "Motor 1000w", "preco": 1250.00, "peso": "6,66kg", "img": "img/shaka/Motor 1000w $1250,00 6,66kg.jpeg" },
      { "nome": "Módulo", "preco": 354.00, "peso": "55gr", "img": "img/shaka/Módulo $354,00 55gr.jpeg" },
      { "nome": "Painel lcd", "preco": 135.00, "peso": "20gr", "img": "img/shaka/Painel lcd $135,00 20g.jpeg" },
      { "nome": "Parabrisa", "preco": 45.00, "peso": "10gr", "img": "img/shaka/Parabrisa $45,00 10g.jpeg" },
      { "nome": "PARALAMA DIANTEIRO", "preco": 190.00, "peso": "30gr", "img": "img/shaka/PARALAMA DIANTEIRO $190,00  30 GR.jpeg" },
      { "nome": "Paralama traseiro", "preco": 145.00, "peso": "45gr", "img": "img/shaka/Paralama traseiro $145,00 45g.jpeg" },
      { "nome": "Pedal ferro dianteiro piloto", "preco": 54.00, "peso": "25gr", "img": "img/shaka/Pedal ferro dianteiro piloto $54,00 25g cada.jpeg" },
      { "nome": "Pedal traseiro garupa", "preco": 64.00, "peso": "45gr", "img": "img/shaka/Pedal traseiro garupa $64,00 45g cada.jpeg" },
      { "nome": "Pisca traseiro", "preco": 55.00, "peso": "5gr", "img": "img/shaka/Pisca traseiro. $55,00 5g cada.jpeg" },
      { "nome": "Plastico acabamento banco pilto", "preco": 35.00, "peso": "5gr", "img": "img/shaka/plastico acabamento banco pilto $35,00 5g.jpeg" },
      { "nome": "Plastico acabamento conversor", "preco": 35.00, "peso": "10gr", "img": "img/shaka/plastico acabamento conversor. $35,00 10g.jpeg" },
      { "nome": "Plastico acabamento inferior", "preco": 25.00, "peso": "5gr", "img": "img/shaka/plastico acabamento inferior $15,00  $25,00  5g.jpeg" },
      { "nome": "Plastico acabamento porta treco", "preco": 25.00, "peso": "5gr", "img": "img/shaka/plastico acabamento porta treco $25,00 5g.jpeg" },
      { "nome": "Plastico banco garupa", "preco": 35.00, "peso": "10gr", "img": "img/shaka/plastico banco garupa $35,00  10g.jpeg" },
      { "nome": "Plastico inferior garupa", "preco": 45.00, "peso": "20gr", "img": "img/shaka/plastico inferior garupa $45,00 20g.jpeg" },
      { "nome": "Plastico pedal traseiro", "preco": 45.00, "peso": "10gr", "img": "img/shaka/Plastico pedal traseiro $45,00 10g cada.jpeg" },
      { "nome": "Plastico suporte porta treco", "preco": 75.00, "peso": null, "img": "img/shaka/plastico suporte porta treco.jpeg" },
      { "nome": "Plástico do cabamento lateral", "preco": null, "peso": "5gr", "img": "img/shaka/Plástico do cabamento lateral 5g und.jpeg" },
      { "nome": "Pneu dianteiro. 2.75-10", "preco": 346.00, "peso": "1,65gr", "img": "img/shaka/Pneu dianteiro. 2.75-10 $346,00 1,65g.jpeg" },
      { "nome": "Porta treco", "preco": 75.00, "peso": "45gr", "img": "img/shaka/Porta treco $75,00 45g.jpeg" },
      { "nome": "Quadro shaka", "preco": 450.00, "peso": "19,80kg", "img": "img/shaka/quadro shaka $450,00 19,80kg.jpeg" },
      { "nome": "Suporte refletor", "preco": 45.00, "peso": "15gr", "img": "img/shaka/Suporte refletor $45,00 15g.jpeg" },
      { "nome": "Tampão da carenagem frontal", "preco": 35.00, "peso": "5gr", "img": "img/shaka/Tampão da carenagem frontal $35,00 5 g.jpeg" },
      { "nome": "Tomada do carregador", "preco": 35.00, "peso": "5gr", "img": "img/shaka/Tomada do carregador. $35,00 5g.jpeg" }
    ]
  },
  "zilla": {
    "nome": "ZILLA",
    "pecas": [
      { "nome": "Acabamento", "preco": null, "peso": "10gr", "img": "img/zilla/acabamento 10gr.jpeg" },
      { "nome": "Acabamento mola", "preco": null, "peso": "5gr", "img": "img/zilla/acabamento mola 5gr cada.jpeg" },
      { "nome": "Acelerador com botão", "preco": null, "peso": "10gr", "img": "img/zilla/acelerador com botão  10GR.jpeg" },
      { "nome": "Alarme", "preco": 126.00, "peso": "5gr", "img": "img/zilla/alarme 5gr.jpeg" },
      { "nome": "Aro", "preco": 206.00, "peso": "1,60kg", "img": "img/zilla/aro 1,60KG.jpeg" },
      { "nome": "Assoalho", "preco": 125.00, "peso": "55gr", "img": "img/zilla/Assoalho 55gr.jpeg" },
      { "nome": "Balanca", "preco": 220.00, "peso": "1,20kg", "img": "img/zilla/balanca 1,20kg..jpeg" },
      { "nome": "Balança", "preco": 220.00, "peso": "1,20kg", "img": "img/zilla/balança 1,20kg.jpeg" },
      { "nome": "Banco passageiro", "preco": null, "peso": "45gr", "img": "img/zilla/Banco passageiro 45GR..jpeg" },
      { "nome": "Banco piloto", "preco": 75.00, "peso": "1kg", "img": "img/zilla/banco piloto 1kg ..jpeg" },
      { "nome": "Bateria", "preco": 298.80, "peso": "7,20kg", "img": "img/zilla/bateria 7,20kg.jpeg" },
      { "nome": "BOTÃO ESQUERDO", "preco": null, "peso": "5gr", "img": "img/zilla/BOTÃO ESQUERDO 5gr.jpeg" },
      { "nome": "Braçadeira do banco", "preco": null, "peso": "5gr", "img": "img/zilla/braçadeira do banco 5gr.jpeg" },
      { "nome": "Cabo do freio dianteiro", "preco": null, "peso": "10gr", "img": "img/zilla/cabo do freio dianteiro 10GR.jpeg" },
      { "nome": "Cabo freio", "preco": 106.80, "peso": "20gr", "img": "img/zilla/cabo freio 20gr.jpeg" },
      { "nome": "Caixa da bateria", "preco": null, "peso": "40gr", "img": "img/zilla/caixa da bateria 40gr.jpeg" },
      { "nome": "Canote banco piloto", "preco": 75.00, "peso": "15gr", "img": "img/zilla/canote banco piloto 15gr.jpeg" },
      { "nome": "Carenagem banco passageiro", "preco": null, "peso": "5gr", "img": "img/zilla/carenagem banco passageiro 5 gramas.jpeg" },
      { "nome": "Carenagem lateral", "preco": 56.00, "peso": "15gr", "img": "img/zilla/carenagem lateral 15gr cada.jpeg" },
      { "nome": "Carenagem peitoral", "preco": 85.00, "peso": "10gr", "img": "img/zilla/carenagem peitoral 10gr.jpeg" },
      { "nome": "CESTO", "preco": null, "peso": "60gr", "img": "img/zilla/CESTO 60GR.jpeg" },
      { "nome": "Chicote bateria", "preco": 315.00, "peso": "15gr", "img": "img/zilla/chicote bateria 15gr.jpeg" },
      { "nome": "Chicote principal", "preco": 315.00, "peso": "20gr", "img": "img/zilla/chicote principal 20gr.jpeg" },
      { "nome": "Conector do carregador", "preco": 346.80, "peso": "5gr", "img": "img/zilla/conector do carregador 5gr.jpeg" },
      { "nome": "Conjunto direção", "preco": 57.00, "peso": "10gr", "img": "img/zilla/conjunto direção 10gr.jpeg" },
      { "nome": "Encosto passageiro", "preco": null, "peso": "65gr", "img": "img/zilla/encosto passageiro 65gr.jpeg" },
      { "nome": "Farol traseiro", "preco": null, "peso": "10gr", "img": "img/zilla/farol traseiro 10gr.jpeg" },
      { "nome": "Freio tambor dianteiro", "preco": 118.80, "peso": "30gr", "img": "img/zilla/freio tambor dianteiro 30gr.jpeg" },
      { "nome": "Freio tambor traseiro", "preco": 118.80, "peso": "50gr", "img": "img/zilla/freio tambor traseiro 50gr.jpeg" },
      { "nome": "Garfo", "preco": null, "peso": "2,30kg", "img": "img/zilla/garfo 2,30kg.jpeg" },
      { "nome": "Guidão", "preco": 115.00, "peso": "1,25kg", "img": "img/zilla/guidão 1,25kg.jpeg" },
      { "nome": "Manete", "preco": 107.00, "peso": "5gr", "img": "img/zilla/manete 5gr cada.jpeg" },
      { "nome": "Manopla", "preco": 42.00, "peso": "10gr", "img": "img/zilla/manopla  10gr.jpeg" },
      { "nome": "Motor", "preco": 1250.00, "peso": "6,10kg", "img": "img/zilla/motor 6,10kg.jpeg" },
      { "nome": "Módulo", "preco": 354.00, "peso": "30gr", "img": "img/zilla/módulo 30GR..jpeg" },
      { "nome": "Painel completo com farol", "preco": null, "peso": "35gr", "img": "img/zilla/painel completo com farol 35GR FOTO LADO.jpeg" },
      { "nome": "Paralama dianteiro", "preco": 190.80, "peso": "20gr", "img": "img/zilla/paralama dianteiro 20gr.jpeg" },
      { "nome": "Paralama traseiro", "preco": 166.80, "peso": "35gr", "img": "img/zilla/paralama traseiro 35gr..jpeg" },
      { "nome": "Pedal de apoio traseiro", "preco": null, "peso": "40gr", "img": "img/zilla/pedal de apoio traseiro 40GR.jpeg" },
      { "nome": "Pedal frontal", "preco": null, "peso": "50gr", "img": "img/zilla/pedal frontal 50gr.jpeg" },
      { "nome": "Pezinho", "preco": null, "peso": "25gr", "img": "img/zilla/pezinho 25gr.jpeg" },
      { "nome": "Plástico banco passageiro", "preco": null, "peso": "15gr", "img": "img/zilla/plástico banco passageiro 15gr.jpeg" },
      { "nome": "Plástico pedal traseiro", "preco": null, "peso": "5gr", "img": "img/zilla/plástico pedal traseiro 5gr cada.jpeg" },
      { "nome": "PNEU 60,90-10", "preco": null, "peso": "1kg", "img": "img/zilla/PNEU 60,90-10   1KG.jpeg" },
      { "nome": "Quadro", "preco": 450.00, "peso": "7,55kg", "img": "img/zilla/quadro 7,55kg.jpeg" },
      { "nome": "Suporte do Cesto", "preco": null, "peso": "15gr", "img": "img/zilla/suporte do Cesto 15GR.jpeg" },
      { "nome": "Suporte manete sensor", "preco": null, "peso": "5gr", "img": "img/zilla/suporte manete sensor 5gr cada.jpeg" },
      { "nome": "Suspensão traseira", "preco": 165.00, "peso": "60gr", "img": "img/zilla/suspensão traseira 60gr.jpeg" },
      { "nome": "Tampa do cesto", "preco": null, "peso": "15gr", "img": "img/zilla/tampa do cesto 15GR.jpeg" }
    ]
  },
  "gataka": {
    "nome": "Gataka",
    "pecas": []
  },
  "pancho": {
    "nome": "Pancho",
    "pecas": []
  },
  "hyphen": {
    "nome": "Hyphen",
    "pecas": []
  },
  "vega": {
    "nome": "Vega",
    "pecas": []
  },
  "kimbo": {
    "nome": "Kimbo",
    "pecas": []
  },
  "juna": {
    "nome": "Juna",
    "pecas": []
  },
  "y1": {
    "nome": "Y1",
    "pecas": []
  },
  "yzl": {
    "nome": "YZL",
    "pecas": []
  },
  "outro": {
    "nome": "Outro",
    "pecas": []
  }
};
